name: Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  CI:
    runs-on: windows-latest                         
    env:
      Solution_Name: Consequences.sln                                  
      dotnet-version: '8.0.x'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3.2.0
      with:
          dotnet-version: ${{ matrix.dotnet-version }} 

    - name: Add Nexus Source
      run:  
        dotnet nuget add source --name fda-nuget "https://www.hec.usace.army.mil/nexus/repository/fda-nuget/"
      
    - name: Install dependencies
      run: dotnet restore -v quiet
        
    - name: Build
      run: dotnet build -v quiet --configuration Release --no-restore

    - name: Test Solution
      run: dotnet test --nologo 
