name: Publish NuGet Packages

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x' # Adjust the .NET version as needed

    - name: Restore dependencies
      run: dotnet restore

    - name: Build for Windows x64
      run: dotnet publish -c Release -r win-x64 --self-contained -p:PublishAot=true

    - name: Build for Linux x64
      run: dotnet publish -c Release -r linux-x64 --self-contained -p:PublishAot=true

    - name: Create version number
      run: |
        TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        VERSION=${TAG#v}
        echo "VERSION=${VERSION}.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

    - name: Pack NuGet packages
      run: dotnet pack -c Release /p:PackageVersion=${{ env.VERSION }}

    - name: Publish NuGet packages to GitHub Packages
      run: dotnet nuget push **/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-x64-${{ env.VERSION }}
        path: |
          **/bin/Release/net8.0/win-x64/publish/

    - name: Upload Linux build artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-x64-${{ env.VERSION }}
        path: |
          **/bin/Release/net8.0/linux-x64/publish/

    - name: Attach Windows artifact to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: "**/bin/Release/net8.0/win-x64/publish/"
        asset_name: windows-x64-${{ env.VERSION }}.zip
        asset_content_type: application/zip

    - name: Attach Linux artifact to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: "**/bin/Release/net8.0/linux-x64/publish/"
        asset_name: linux-x64-${{ env.VERSION }}.zip
        asset_content_type: application/zip
